version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - dependabot
      - dependencies
      - github-actions
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    labels:
      - dependabot
      - dependencies
      - crates
  - package-ecosystem: npm
    directory: /docs/site
    schedule:
      interval: daily
    labels:
      - dependabot
      - dependencies
      - node
