#!/usr/bin/env sh
#MISE description="Lint markdown files"
#MISE alias=["l:md", "l:markdown", "lint:md"]

set -e

markdownlint-cli2 --config .config/.markdownlint.yml "*.md" "**/*.md" "#.cargo" "#.mise" "#.mise-data" "#coverage" "#.github/PULL_REQUEST_TEMPLATE.md" "#target" "#tmp" "#**/node_modules" "$@"
