[env]
GEST_DATA_DIR = "${XDG_DATA_HOME:-$HOME/.config}/gest/2f8de7bc06014bd7"

[settings]
env_shell_expand = true

[task_config]
includes = ["tasks"]

[tasks.format]
description = "Format all files"
alias = ["fmt"]
depends = ["format:**"]

[tasks.lint]
description = "Lint all files"
alias = ["l"]
depends = ["lint:**"]

[tools]
bun = "latest"
"cargo:cargo-audit" = "latest"
"cargo:cargo-llvm-cov" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:cargo-outdated" = "latest"
"cargo:cargo-sort" = "latest"
editorconfig-checker = "latest"
gh = "latest"
markdownlint-cli2 = "latest"
nodejs = "lts"
taplo = "latest"
usage = "latest"
yamlfmt = "latest"

[[tools.rust]]
components = "clippy"
version = "latest"

[[tools.rust]]
components = "rustfmt"
version = "nightly"
