name: Build
permissions:
  contents: read
  pull-requests: write
on:
  push:
    branches:
      - main
    tags:
      - "[0-9]+.*"
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - name: Lint
        run: mise run lint
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - name: Check
        run: mise run check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - name: Test
        run: mise run test
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - name: Build
        run: mise run build
